# The fix is needed when gcc version 12 is used
# This fix may be removed if SDP gcc is updated to newer version in future
CCFLAGS_aarch64 += -Wc,--param=min-pagesize=0

include ../../../../common.mk
